"""Generate diff.md from the two real traces. Pure evidence, no prose."""
from __future__ import annotations

import sys
from pathlib import Path

PROOF = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROOF))
from proof_lib import trace_util  # noqa: E402


def main() -> int:
    ref = trace_util.load(sys.argv[1] if len(sys.argv) > 1 else PROOF / "runs/reference/run.json")
    lg = trace_util.load(sys.argv[2] if len(sys.argv) > 2 else PROOF / "runs/langgraph/run.json")
    out = Path(sys.argv[3]) if len(sys.argv) > 3 else PROOF / "expected/diff.md"

    re, le = trace_util.essential_projection(ref), trace_util.essential_projection(lg)
    lines = [
        "# Trace Diff — reference vs langgraph",
        "",
        "_Generated by `proof/runtimes/diff.py` from two real runs. Do not edit by hand._",
        "",
        "## Same (essential — the portability claim)",
        "",
        "| Property | reference | langgraph | match |",
        "| --- | --- | --- | :--: |",
        f"| workflow graph (steps) | {len(re['workflow_graph'])} | {len(le['workflow_graph'])} | "
        f"{'✓' if re['workflow_graph']==le['workflow_graph'] else '✗'} |",
        f"| final outcome | {re['outcome']} | {le['outcome']} | "
        f"{'✓' if re['outcome']==le['outcome'] else '✗'} |",
        f"| verification checks pass | "
        f"{sum(1 for v in re['verifications'] if v['status']=='pass')}/{len(re['verifications'])} | "
        f"{sum(1 for v in le['verifications'] if v['status']=='pass')}/{len(le['verifications'])} | "
        f"{'✓' if re['verifications']==le['verifications'] else '✗'} |",
        "",
        "### Artifact content hashes",
        "",
        "| Artifact | sha256 | identical |",
        "| --- | --- | :--: |",
    ]
    for path, h in re["artifacts"].items():
        same = re["artifacts"].get(path) == le["artifacts"].get(path)
        lines.append(f"| `{path}` | `{h}` | {'✓' if same else '✗'} |")

    lines += [
        "",
        "## Different (non-essential — NOT part of the claim)",
        "",
        "| Property | reference | langgraph |",
        "| --- | --- | --- |",
        f"| engine | `{ref['engine']['type']}` | `{lg['engine']['type']}` ({lg['engine'].get('version','')}) |",
        f"| orchestrator | `{ref['engine'].get('orchestrator','')}` | `{lg['engine'].get('orchestrator','')}` |",
        f"| started_at | {ref['started_at']} | {lg['started_at']} |",
        f"| ended_at | {ref['ended_at']} | {lg['ended_at']} |",
        f"| executed_order | `{ref['executed_order']}` | `{lg['executed_order']}` |",
        "",
        "> The executed orders may differ in the ordering of fan-out siblings",
        "> (e.g. `s3`/`s4`, which both depend only on `s2`). Both are valid",
        "> topological orders of the same dependency graph — `verify.py` asserts",
        "> exactly that, not byte-identical ordering.",
        "",
    ]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
